apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodforweather-deployment
  namespace: development
  labels:
    app: foodforweather
spec:
  replicas: 3
  template:
    metadata:
      name: foodforweather
      labels:
        app: foodforweather
    spec:
      containers:
        - name: foodforweather-container
          image: brittanybn/food-for-weather:updated
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: foodforweather-config
      restartPolicy: Always
  selector:
    matchLabels:
      app: foodforweather
